task:
  name: Test (Linux)
  container:
    image: wezm/steno-engine-ci:latest
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  test_script: cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

task:
  name: Test (Mac OS)
  osx_instance:
    image: high-sierra-base
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  install_rust_script: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
  test_script: 'PATH="$HOME/.cargo/bin:$PATH" cargo test'
  before_cache_script: rm -rf $CARGO_HOME/registry/index

task:
  name: Test (Windows)
  windows_container:
    image: cirrusci/windowsservercore:2016
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.toml
  install_rust_script: 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
  test_script: 'PATH="$HOME/.cargo/bin:$PATH" cargo test'
  before_cache_script: rm -rf $CARGO_HOME/registry/index
