#!/usr/bin/env bash

empty -f -L cargo-test.log -p empty.pid cargo test
while [ -e empty.pid ]; do
  sleep 1
done
cat cargo-test.log
if grep '^test result: FAILED' cargo-test.log; then
  exit 1
else
  exit 0
fi
